### ISSUE TITLE
Support for Titan Panel

### ISSUE THREAD

**Issue by MetalHeadSeven** [lamboley/Z-AllTimePlayed#2]
Thanks for creating AllTimePlayed!  Would it be possible to add support for Titan Panel?

**Comment by lamboley** [comment]
Yeah it is possible, i'm working on it.
Currently it throw an error when tooltip are disable in Titan Panel.
I will upload a fix as soon as possible.

**Comment by MetalHeadSeven** [comment]
Thanks very much.  I like to keep buttons on my minimum.

**Comment by lamboley** [comment]
Support for addon Titan Panel, Bazooka, etc is uploaded in the version 1.03.
Sorry, for dark reason I have renamed the addon so u will have to recreate the database by login on eachs characters u have again.

**Comment by MetalHeadSeven** [comment]
Thanks. Works perfectly.
